project:
  type: book
  output-dir: docs
  
book:
  title: Probability Theory for Econometricians
  downloads: [pdf]
  author: Sven Otto
  sidebar: false
  navbar: false
  date: today
  date-format: "MMMM D, YYYY"
  # description: "Random variables, limit theorems, and the asymptotic theory toolbox"
  search: true
  page-navigation: true
  open-graph: true
  chapters:
    - index.qmd
    - part1_distribution.qmd
    - part2_expectation.qmd
    - part3_covariance.qmd
    # - sec02_probability.qmd
    # - sec03_dependence.qmd
    # - stat1_data.qmd
    # - stat3_probability.qmd
    # - stat4_expectation.qmd
    # - stat5_conditional.qmd
format:
  html:
    theme:
      light: [default, theme.scss]
      dark: [default, darkly, theme.scss]
    html-math-method: katex
    monofont: Fira Mono
    mathfont: Leto
    linkcolor: green
    number-sections: true
    code-link: true
    reference-links: true
    reference-location: margin
    knitr:
      opts_chunk:
        fig.align: center
    fig-align: center
  pdf:
    include-in-header: preamble-latex.tex
    documentclass: scrreprt
    fig-align: center
    fig-pos: 'htbp'  # Add this line to control figure placement
    pdf-engine: pdflatex
  
resources:
  - CNAME