project:
  type: book
  output-dir: docs
  
book:
  title: Probability Theory for Econometricians
  downloads: [pdf]
  author: Sven Otto
  sidebar: false
  navbar: false
  date: today
  date-format: "MMMM D, YYYY"
  description: "Random variables, limit theorems, and the asymptotic theory toolbox"
  search: true
  page-navigation: true
  open-graph: true
  chapters:
    - index.qmd
    - 01_randomvariables.qmd
    - 02_probability.qmd
    - 03_expectations.qmd
    - 04_conditioning.qmd

format:
  html:
    theme:
      light: [default, theme.scss]
      dark: [default, darkly, theme.scss]
    html-math-method: katex
    monofont: Fira Mono
    mathfont: Leto
    linkcolor: green
    number-sections: true
    code-link: true
    reference-links: true
    reference-location: margin
    knitr:
      opts_chunk:
        fig.align: center
    fig-align: center
  pdf:
    include-in-header: preamble-latex.tex
    documentclass: scrreprt
    fig-align: center
    pdf-engine: pdflatex
  
resources:
  - CNAME